### ISSUE TITLE
flask db migrate upgrade/downgrade doesn't work as expected : no downgrade in the alembic_version table...

### ISSUE THREAD

**Issue by rlabrador** [nickjj/flask-db#12]
Hello. Me again.

ran: flask db migrate revision -m "Category updates for a new colum blabla"

My revision's generated file has the number 8c886408a308.
Content:
''
def upgrade():
    op.add_column('category', sa.Column('blabla', sa.String))
    op.create_index("ix_category_blabla", "category", ["blabla"], unique=True)

def downgrade():
    op.drop_column('category', sa.Column('blabla', sa.String))
    op.drop_index("ix_category_blabla")
''
Command : flask db migrate upgrade 8c886408a308 : OK
Command : flask db migrate downgrade 8c886408a308: OK
(No errors)
The "blabla" column is added by the upgrade, not removed from the category table by the downgrade.
The "8c886408a308" number still present in the alembic_version table.

Any ideas?
Thanks.

**Comment by nickjj** [comment]
Hi,

At this point we've left the world of Flask-DB and entered the world of Alembic (the tool that's handling database migrations). Flask-DB doesn't handle any of this logic, it directly forwards any `migrate` command to Alembic. That is mentioned here: https://github.com/nickjj/flask-db#migrate

You may want to message them directly for questions around how database migrations work.

Your migration looks pretty normal based on the information you provided.
