### ISSUE TITLE
[BUG] IDE giving me syntax error

### ISSUE THREAD

**Issue by dwreeves** [nickjj/flask-db#4]
I like this tool, I think it's a good way to do migrations with Flask. I like that it doesn't involve touching my app code with a "migrate" object, it creates a good boilerplate `env.py` file from the get-go. There's just one problem...

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/31971762/120407210-ac2b0a80-c31a-11eb-89eb-61dad1b7c127.png">

The problem is my IDE. PyCharm Professional 202.3 believes that this package contains is a syntax error because it sees a `.py` file called `env.py` and doesn't realize it's a template. The error is here:

```python
from $CURRENT_APP_IMPORT_NAME import create_app  # noqa: E999
```

It's also extremely tedious to tell PyCharm to not look at this. This makes it a bit... annoying to incorporate into my project, as now the whole project folder has a red line underneath.

**Comment by nickjj** [comment]
Hi,

- What version of Flask-DB are you using?
- What OS are you're using?
- What terminal shell are you using?

That value should have been replaced with the import path of your project at the point of running the init command.

As for touching your app code with a migrate object, that's just how Alembic works. This tool is mainly a wrapper around Alembic for the migration bits.

**Comment by dwreeves** [comment]
- Latest version on pypi, so `0.3.1`.
- OS X 10.15: Catalina
- zsh

> That value should have been replaced with the import path of your project at the point of running the init command.

Yes, I understand. The site-package inside the venv causes the error, not the folder for migrations itself. The red line in the screenshot I'm showing is highlighting my `venv`.

> As for touching your app code with a migrate object, that's just how Alembic works. This tool is mainly a wrapper around Alembic for the migration bits.

I meant inside the app itself. I meant I appreciated I don't have a `Migrate(db=db).init_app(app)`. I've used Alembic before in a FastAPI context.

**Comment by nickjj** [comment]
Oh, so the "real" file is working.

I suppose I could change the placeholder to be something that's valid Python.

If you remove the `$` does PyCharm treat it as valid syntax?

**Comment by dwreeves** [comment]
Yep, that's the problem.

Removing the `$` appears to work. PyCharm only gives you the nasty red lines for invalid Python syntax inside `*.py` files.

A few other solutions include substituting `env.py` with `env.py.txt` or making it a Jinja template `env.py.jinja2` then rendering. But removing the dollar sign is definitely the most straightforward approach.

**Comment by nickjj** [comment]
Ok thanks, I've pushed `0.3.2` to PyPI which removes the `$`.

Should be good to go.

**Comment by dwreeves** [comment]
Thanks!
