### ISSUE TITLE
Can I use it with FastAPI?

### ISSUE THREAD

**Issue by karolzlot** [nickjj/flask-db#6]
I see Flask in name of project, but does it really depend on Flask?

I see it as a CLI to Alembic and SQLAlchemy.

**Comment by nickjj** [comment]
It imports a few things from Flask like `current_app` and uses Flask's `with_appcontext`.

**Comment by nickjj** [comment]
Going to close this since I believe it addresses your question. I can't see a reasonable way around having a dependency on Flask without complicating the library.
