### ISSUE TITLE
How to access fixtures for `flask db seed`?

### ISSUE THREAD

**Issue by sgraaf** [nickjj/flask-db#7]
Hi there!

For the purposes of seeding my DB, I have a directory `/db/fixtures`, which contains fixtures in the form `JSON`-files. When I try to access these fixtures by means of relative path(s), I run into problems. As `seeds.py` is executed by means of `exec` (rather than imported or called directly in some other way), any relative path is relative to `flask_db/cli.py` (instead of `seeds.py`)...

As such, I would love to know if you have any tips or tricks for my specific use-case? Is there any way to have my fixtures stored separately (outside my `seeds.py` file), after which I can access them through relative paths, rather than (hard-coded) absolute paths?

Many thanks in advance!

**Comment by nickjj** [comment]
Hi,

What if you access your `PYTHONPATH`, assuming it's set (it should be)? If that's set to `.` that should drop you into the root of your project and then you can access your relative `db/fixtures/user.json` path for the rest.

**Comment by nickjj** [comment]
If that doesn't work for you, the seeds file has access to Flask's `current_app` which means you could reach in and grab `current_app.root_path` to get your app's root path and then like the above solution you can access your fixtures with a relative path.

**Comment by sgraaf** [comment]
> 
> 
> Hi,
> 
> What if you access your `PYTHONPATH` as an env var, assuming it's set (it should be)? If that's set to `.` that should drop you into the root of your project and then you can access your relative `db/fixtures/user.json` path for the rest.

This worked like a charm! Thanks for the quick reply! :)
